# Generated by Django 5.1.6 on 2025-06-20 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationno', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('fathername', models.CharField(default='', max_length=30)),
                ('mothername', models.CharField(default='', max_length=30)),
                ('mobno', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('course', models.CharField(default='', max_length=30)),
                ('batchtime', models.CharField(default='', max_length=30)),
                ('Photo', models.ImageField(default='', upload_to='static/studentimage')),
                ('fee', models.CharField(default='', max_length=30)),
                ('remaningfee', models.CharField(default='', max_length=50)),
                ('DateNow', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_Admission', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationno', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('fathername', models.CharField(default='', max_length=30)),
                ('mothername', models.CharField(default='', max_length=30)),
                ('mobno', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('course', models.CharField(default='', max_length=30)),
                ('batchtime', models.CharField(default='', max_length=30)),
                ('Photo', models.ImageField(default='', upload_to='static/studentimage')),
                ('fee', models.CharField(default='', max_length=30)),
                ('remaningfee', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
