# Generated by Django 5.1.6 on 2026-02-18 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moo', '0002_alter_aa_date_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Enroll_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationno', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('fathername', models.CharField(default='', max_length=30)),
                ('mothername', models.CharField(default='', max_length=30)),
                ('mobno', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('course', models.CharField(default='', max_length=30)),
                ('batchtime', models.CharField(default='', max_length=30)),
                ('Photo', models.ImageField(blank=True, default='StudentEnroll/default.jpg', null=True, upload_to='static/StudentEnroll')),
                ('fee', models.CharField(default='', max_length=30)),
                ('remaningfee', models.CharField(default='', max_length=50)),
                ('DateNow', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_Admission', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
