# Generated by Django 5.1.6 on 2026-02-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moo', '0003_student_enroll_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enroll_model',
            name='Photo',
            field=models.ImageField(blank=True, default='studentimage/default.jpg', null=True, upload_to='static/StudentEnroll'),
        ),
    ]
