# Generated by Django 5.1.6 on 2026-03-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moo', '0004_alter_student_enroll_model_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aa',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aa',
            name='remaningfee',
            field=models.IntegerField(default=0),
        ),
    ]
