# Generated by Django 5.1.6 on 2026-03-04 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moo', '0005_alter_aa_fee_alter_aa_remaningfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='aa',
            name='paidfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bb',
            name='DateNow',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bb',
            name='Date_Admission',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='bb',
            name='paidfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_enroll_model',
            name='paidfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bb',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bb',
            name='remaningfee',
            field=models.IntegerField(default=0),
        ),
    ]
