# Generated by Django 5.1.6 on 2026-03-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moo', '0006_aa_paidfee_bb_datenow_bb_date_admission_bb_paidfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aa',
            name='FEES_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aa',
            name='NEXT_FEES_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEES_DATE', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moo.aa')),
            ],
        ),
    ]
